select `a`.`id`                                     AS `id`,
       `b`.`formid`                                 AS `formid`,
       `b`.`ipaddr`                                 AS `ipaddr`,
       `a`.`paid amount`                            AS `paid amount`,
       `a`.`Paid or not?`                           AS `Paid or not?`,
       `a`.`Task Start or Last Pmt Date`            AS `Task Start or Last Pmt Date`,
       `a`.`Task Status`                            AS `Task Status`,
       `b`.`time`                                   AS `time`,
       `a`.`Wait files`                             AS `Wait files`,
       `a`.`Client Name/Payer Name`                 AS `Client Name/Payer Name`,
       `a`.`Task Type`                              AS `Task Type`,
       `a`.`application fee need to pay for client` AS `application fee need to pay for client`,
       `a`.`what to file`                           AS `what to file`,
       `a`.`Due date`                               AS `Due date`,
       `a`.`Task Period`                            AS `Task Period`,
       `a`.`Received files`                         AS `Received files`,
       `a`.`how to file refund tax`                 AS `how to file refund tax`,
       `a`.`get a quote or not`                     AS `get a quote or not`,
       `a`.`Task assigned to`                       AS `Task assigned to`,
       `a`.`2020 W2 efiled?`                        AS `2020 W2 efiled?`,
       `a`.`20Q4 941`                               AS `20Q4 941`,
       `a`.`20Q4 940`                               AS `20Q4 940`,
       `a`.`20Q4 DE9`                               AS `20Q4 DE9`,
       `a`.`20Q4 DE9C`                              AS `20Q4 DE9C`,
       `a`.`21 UI update`                           AS `21 UI update`,
       `a`.`Unpaid period`                          AS `Unpaid period`,
       `a`.`file 1`                                 AS `file 1`,
       `a`.`file 2`                                 AS `file 2`,
       `a`.`file 1 status`                          AS `file 1 status`,
       `a`.`file 2 status`                          AS `file 2 status`,
       `b`.`data`                                   AS `data`,
       `b`.`urls`                                   AS `urls`,
       `b`.`clean_data`                             AS `clean_data`,
       `a`.`backoffice note`                        AS `backoffice note`,
       `b`.`name`                                   AS `name`,
       `b`.`email`                                  AS `email`,
       `b`.`phone`                                  AS `phone`,
       `b`.`expedited`                              AS `expedited`
from (`149512055`.`aq_task` `a`
         join `149512055`.`wp_cp_calculated_fields_form_posts` `b`)
where `a`.`id` = `b`.`id`